/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenuItem;

/**
 *
 * @author Julia Dalcamini
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {

    public ViewMenuPrincipal newview;

    /**
     * Creates new form MenuPrincipal
     */
    public ViewMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOptions = new javax.swing.JMenu();
        MenuNewContact = new javax.swing.JMenuItem();
        MenuListContact = new javax.swing.JMenuItem();
        MenuCloseSystem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuOptions.setText("Opções");

        MenuNewContact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuNewContact.setText("Novo Contato");
        MenuNewContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNewContactActionPerformed(evt);
            }
        });
        MenuOptions.add(MenuNewContact);

        MenuListContact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuListContact.setText("Listar Contatos");
        MenuListContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListContactActionPerformed(evt);
            }
        });
        MenuOptions.add(MenuListContact);

        MenuCloseSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuCloseSystem.setText("Fechar Sistema");
        MenuOptions.add(MenuCloseSystem);

        jMenuBar1.add(MenuOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNewContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNewContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuNewContactActionPerformed

    private void MenuListContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuListContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCloseSystem;
    private javax.swing.JMenuItem MenuListContact;
    private javax.swing.JMenuItem MenuNewContact;
    private javax.swing.JMenu MenuOptions;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMenuCloseSystem() {
        return MenuCloseSystem;
    }

    public void setMenuCloseSystem(JMenuItem MenuCloseSystem) {
        this.MenuCloseSystem = MenuCloseSystem;
    }

    public JMenuItem getMenuListContact() {
        return MenuListContact;
    }

    public void setMenuListContact(JMenuItem MenuListContact) {
        this.MenuListContact = MenuListContact;
    }

    public JMenuItem getMenuNewContact() {
        return MenuNewContact;
    }

    public void setMenuNewContact(JMenuItem MenuNewContact) {
        this.MenuNewContact = MenuNewContact;
    }
    
}
